# Generated by Django 2.1 on 2018-08-30 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursoshandler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cursos',
            name='docentes',
        ),
        migrations.AddField(
            model_name='docentes',
            name='curso',
            field=models.ManyToManyField(blank=True, related_name='docentes', to='cursoshandler.Cursos'),
        ),
    ]
