# Generated by Django 2.1 on 2018-08-30 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursoshandler', '0002_auto_20180829_2259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docentes',
            name='curso',
        ),
        migrations.AddField(
            model_name='cursos',
            name='docentes',
            field=models.ManyToManyField(blank=True, related_name='cursos', to='cursoshandler.Docentes'),
        ),
    ]
