# Generated by Django 2.1 on 2018-08-29 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inputs',
            fields=[
                ('id_input', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True)),
                ('text', models.CharField(max_length=400)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('raw_input', models.CharField(blank=True, max_length=3000)),
                ('solved', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Input',
                'verbose_name_plural': 'Inputs',
                'db_table': 'inputs',
                'default_related_name': 'inputs',
            },
        ),
        migrations.CreateModel(
            name='SocialNetworks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_account', models.CharField(max_length=10)),
                ('user_name', models.CharField(max_length=30)),
                ('social_network', models.CharField(choices=[('T', 'Twitter'), ('F', 'Facebook'), ('TG', 'Telegram')], default='TG', max_length=2)),
            ],
            options={
                'verbose_name': 'SocialNetwork',
                'verbose_name_plural': 'SocialNetworks',
                'db_table': 'socialnetworks',
                'default_related_name': 'socialnetworks',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('id_number', models.CharField(max_length=20, unique=True)),
                ('id_oc', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('inputs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='chatbothandler.Inputs')),
                ('sn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='chatbothandler.SocialNetworks')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
                'default_related_name': 'users',
            },
        ),
    ]
