# Generated by Django 2.1 on 2018-08-29 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nluengine', '0005_auto_20180828_2227'),
        ('chatbothandler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputs',
            name='intent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='nluengine.Intents'),
        ),
    ]
