# Generated by Django 2.1 on 2018-08-29 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbothandler', '0002_inputs_intent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialnetworks',
            name='id_account',
            field=models.CharField(default=9999999999, max_length=10),
        ),
        migrations.AlterField(
            model_name='users',
            name='id_number',
            field=models.CharField(default=9999999999, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='id_oc',
            field=models.CharField(default=9999999999, max_length=20, unique=True),
        ),
    ]
