# Generated by Django 2.1 on 2018-08-29 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbothandler', '0003_auto_20180828_2233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='sn',
            new_name='social_network',
        ),
    ]
