# Generated by Django 2.1 on 2018-08-29 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbothandler', '0004_auto_20180828_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputs',
            name='intent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='nluengine.Intents'),
        ),
    ]
