# Generated by Django 2.1 on 2018-08-29 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbothandler', '0007_auto_20180828_2322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialnetworks',
            name='user',
        ),
        migrations.AddField(
            model_name='users',
            name='social_network',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='chatbothandler.SocialNetworks'),
        ),
    ]
