# Generated by Django 2.1 on 2018-08-29 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbothandler', '0009_auto_20180829_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='social_network',
        ),
        migrations.AddField(
            model_name='socialnetworks',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='socialnetworks', to='chatbothandler.Users'),
        ),
    ]
