# Generated by Django 2.1 on 2018-08-29 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbothandler', '0012_auto_20180829_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputs',
            name='source',
            field=models.CharField(choices=[('T', 'Twitter'), ('F', 'Facebook'), ('TG', 'Telegram')], default='TG', max_length=2),
        ),
    ]
